Creating random user-agent to fix broken streams
marmelo/streaming-pt pull request #52
Opened 2020-09-04 10:04 UTC by fimdomeio

This introduces a random generated string that is used as the user agent.

Should fix most problems reported in #51

2020-09-04 10:44 UTC, marado commented on tv.sh
> +echo $USER_AGENT
We don't really need this echo around...

2020-09-04 10:46 UTC, marado requested changes
That extra echo can be removed

2020-09-04 12:46 UTC, fimdomeio commented
fixed

2020-09-26 22:50 UTC, marado approved these changes

2020-09-27 00:20 UTC, marmelo approved these changes

2020-09-27 00:21 UTC, merged

2020-09-27 00:22 UTC, marmelo commented
Thanks @fimdomeio, @marado!
Sorry for the delay.